-- Add avatar support to agents table.
-- avatar_path: relative path to the avatar image file on disk
-- avatar_description: text description generated by vision.capture MCP (injected into system prompt)
ALTER TABLE agents ADD COLUMN avatar_path TEXT;
ALTER TABLE agents ADD COLUMN avatar_description TEXT;
