use anyhow::Context;
use std::path::{Path, PathBuf};
use tracing::info;

/// Binary name for the current platform
fn binary_name() -> &'static str {
    if cfg!(windows) {
        "clotocore.exe"
    } else {
        "clotocore"
    }
}

/// Copy the marketplace install engine that ships beside the kernel binary
/// into the install prefix, so the installed kernel can find it next to
/// itself (`managers::installer` looks in the executable's directory).
///
/// Returns the installed path, or `None` when no engine was found beside
/// the source binary — an installation made from a bare `clotocore` file
/// rather than the release archive. That is reported, not fatal: the kernel
/// boots without the engine and refuses marketplace installs with a clear
/// error instead of failing silently.
pub(crate) fn stage_engine(src_dir: &Path, prefix: &Path) -> anyhow::Result<Option<PathBuf>> {
    let name = crate::managers::installer::binary_name();
    let src = src_dir.join(name);
    if !src.is_file() {
        return Ok(None);
    }
    let dst = prefix.join(name);
    if src == dst {
        return Ok(Some(dst));
    }
    std::fs::copy(&src, &dst)
        .with_context(|| format!("Failed to copy {} to {}", src.display(), dst.display()))?;
    crate::platform::set_executable_permission(&dst)?;
    Ok(Some(dst))
}

/// Hand the whole install prefix to the service user. The unit runs as that
/// user and must be able to read `.env` (0600) and write under `data/`.
#[cfg(unix)]
fn chown_recursive(prefix: &Path, user: &str) -> anyhow::Result<()> {
    let status = std::process::Command::new("chown")
        .args(["-R", user])
        .arg(prefix)
        .status()
        .with_context(|| format!("Failed to run chown -R {user} {}", prefix.display()))?;
    if !status.success() {
        anyhow::bail!(
            "chown -R {user} {} failed with exit code {:?}",
            prefix.display(),
            status.code()
        );
    }
    Ok(())
}

/// Generate .env file content
fn env_template(prefix: &Path, api_key: &str) -> String {
    let timestamp = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
    let db_path = prefix.join("data").join("cloto_memories.db");

    format!(
        r#"# ============================================================
# ClotoCore Configuration
# Generated by ClotoCore install on {timestamp}
# ============================================================

# --- Server ---
PORT=8081
RUST_LOG=info

# --- Security (Principle #5: Strict Permission Isolation) ---
# Admin API key for protected endpoints (plugin config, permissions, shutdown).
# REQUIRED: Without this, all admin operations are denied in release builds.
# Pass via X-API-Key header.
CLOTO_API_KEY={api_key}

# --- Database ---
# SQLite database path. The data/ directory is created automatically.
DATABASE_URL=sqlite:{db_path}

# --- AI Provider API Keys ---
# Uncomment and set to enable reasoning engines.
# DEEPSEEK_API_KEY=
# CEREBRAS_API_KEY=

# --- Consensus (Principle #8: Dynamic Intelligence Orchestration) ---
# Multi-engine deliberation: a message prefixed with "consensus:" fans out to
# the agent's assigned reasoning engines, and a synthesizer engine merges the
# independent proposals into one answer delivered as the agent's response.
# Engines are sourced from the agent's granted engine servers — assign at
# least CONSENSUS_MIN_PROPOSALS engines (default 2) to the agent in the
# Dashboard. CONSENSUS_ENGINES only narrows that per-agent set
# (comma-separated IDs; empty = use all of the agent's engines) — it never
# adds an engine the agent was not assigned.
# CONSENSUS_ENGINES=

# --- Agent ---
# DEFAULT_AGENT_ID=agent.cloto_default

# --- Tuning ---
# MAX_EVENT_DEPTH=10
# PLUGIN_EVENT_TIMEOUT_SECS=30
# MEMORY_CONTEXT_LIMIT=10

# --- Remote Update (Principle #8: HITL) ---
# GitHub repository for update distribution (owner/repo).
# Used by GET /api/system/update/check and POST /api/system/update/apply.
# CLOTO_UPDATE_REPO=Cloto-dev/ClotoCore

# --- Network ---
# CORS origins (comma-separated). The embedded dashboard is served from
# the same origin, so CORS is only needed for external API clients.
# CORS_ORIGINS=http://localhost:5173

# --- MCP Servers ---
# Path to clotohub-servers/servers directory.
# Required for MCP server auto-discovery from mcp.toml.
# CLOTO_MCP_SERVERS=C:\path\to\clotohub-servers\servers

# --- Plugin Network Access (Principle #5) ---
# Additional hosts that plugins with NetworkAccess permission may reach.
# Default whitelist: api.deepseek.com, api.cerebras.ai, api.openai.com, api.anthropic.com
# ALLOWED_HOSTS=
"#,
        timestamp = timestamp,
        api_key = api_key,
        db_path = db_path.display(),
    )
}

/// Install Cloto to the specified prefix directory
pub async fn install(prefix: PathBuf, service: bool, user: Option<String>) -> anyhow::Result<()> {
    println!("=== ClotoCore Installer ===");
    println!("  Prefix:  {}", prefix.display());
    println!("  Service: {}", service);
    println!();

    // 1. Create directories
    let scripts_dir = prefix.join("scripts");
    let data_dir = prefix.join("data");
    std::fs::create_dir_all(&scripts_dir)
        .with_context(|| format!("Failed to create {}", scripts_dir.display()))?;
    std::fs::create_dir_all(&data_dir)
        .with_context(|| format!("Failed to create {}", data_dir.display()))?;
    info!("📁 Created directories");

    // 2. Copy self (binary) to prefix
    let src_exe = std::env::current_exe().context("Cannot determine current executable path")?;
    let dst_exe = prefix.join(binary_name());
    if src_exe == dst_exe {
        info!("📦 Binary already in place");
    } else {
        std::fs::copy(&src_exe, &dst_exe)
            .with_context(|| format!("Failed to copy binary to {}", dst_exe.display()))?;
        crate::platform::set_executable_permission(&dst_exe)?;
        info!("📦 Installed binary: {}", dst_exe.display());
    }

    // 2b. Marketplace install engine: ships beside the kernel in the release
    //     archive and must end up beside it in the prefix too.
    let engine_src_dir = src_exe
        .parent()
        .map_or_else(|| prefix.clone(), Path::to_path_buf);
    let engine = stage_engine(&engine_src_dir, &prefix)?;
    if let Some(p) = &engine {
        info!("📦 Installed marketplace engine: {}", p.display());
    } else {
        tracing::warn!(
            "marketplace install engine ({}) not found beside {}; marketplace installs will be refused until it is placed in {}",
            crate::managers::installer::binary_name(),
            engine_src_dir.display(),
            prefix.display()
        );
    }

    // 3. Generate .env (skip if exists)
    let env_path = prefix.join(".env");
    if env_path.exists() {
        info!("ℹ️  .env already exists, skipping");
    } else {
        let api_key = crate::apikey::generate();
        let env_content = env_template(&prefix, &api_key);
        std::fs::write(&env_path, env_content).context("Failed to write .env")?;
        // Restrict .env permissions (contains CLOTO_API_KEY)
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&env_path, std::fs::Permissions::from_mode(0o600))
                .context("Failed to set .env permissions to 0600")?;
        }
        // bug-463: the Unix 0600 hardening had no Windows counterpart, leaving
        // the admin-key file readable by the local Users group under the default
        // ProgramData ACL. Strip inheritance and grant only the current user.
        #[cfg(windows)]
        {
            if let Ok(user) = std::env::var("USERNAME") {
                if !user.is_empty() {
                    let status = std::process::Command::new("icacls")
                        .args([
                            &env_path.display().to_string(),
                            "/inheritance:r",
                            "/grant:r",
                            &format!("{user}:F"),
                        ])
                        .status();
                    if !matches!(status, Ok(s) if s.success()) {
                        tracing::warn!("Failed to tighten .env ACL via icacls; secret may be readable by other local users");
                    }
                }
            }
        }
        info!("🔑 Generated .env with CLOTO_API_KEY");
        println!("  CLOTO_API_KEY has been auto-generated. Save it securely:");
        println!("  {}", api_key);
    }

    // 3b. A service user other than the installer's must own what it runs.
    #[cfg(unix)]
    if let Some(u) = user.as_deref() {
        chown_recursive(&prefix, u)?;
        info!("👤 Prefix owned by {u}");
    }

    // 4. Register service (optional)
    if service {
        crate::platform::install_service(&prefix, user.as_deref())?;
    }

    // 4b. Defender install receipt (DEFENDER_DESIGN.md §3): ledger every
    // path this install created. Best-effort — never fails the install.
    {
        use crate::defender::footprint::ReceiptEntry;
        let mut entries = vec![ReceiptEntry::file("binary", &dst_exe)];
        if let Some(p) = &engine {
            entries.push(ReceiptEntry::file("engine", p));
        }
        entries.extend([
            ReceiptEntry::dir("install_prefix", &prefix),
            ReceiptEntry::dir("install_scripts", &scripts_dir),
            ReceiptEntry::dir("install_data", &data_dir),
            ReceiptEntry::file("env", &env_path).secret(),
        ]);
        if service {
            entries.push(ReceiptEntry::service("service", service_name()));
        }
        crate::defender::footprint::record(&crate::config::data_dir(), entries);
    }

    // 5. Summary
    println!();
    println!("=== Installation complete ===");
    println!();
    println!(
        "  To run manually:  cd {} && ./{}",
        prefix.display(),
        binary_name()
    );
    if service {
        if cfg!(windows) {
            println!("  As service:       sc.exe start Cloto");
        } else {
            println!("  As service:       sudo systemctl start cloto");
        }
    }
    println!("  Dashboard:        http://localhost:8081");
    println!();

    Ok(())
}

/// OS service identifier as registered by `crate::platform::install_service`.
fn service_name() -> &'static str {
    if cfg!(windows) {
        "Cloto"
    } else if cfg!(target_os = "macos") {
        "com.cloto.system"
    } else {
        "cloto"
    }
}

/// Uninstall Cloto from the specified prefix directory
pub async fn uninstall(prefix: PathBuf) -> anyhow::Result<()> {
    println!("=== ClotoCore Uninstaller ===");

    // Stop and remove service
    let _ = crate::platform::uninstall_service();

    if prefix.exists() {
        println!("Removing {}...", prefix.display());
        std::fs::remove_dir_all(&prefix)
            .with_context(|| format!("Failed to remove {}", prefix.display()))?;
    }

    // Defender install receipt: drop the entries this path removed
    // (best-effort; the user-data dir itself is untouched by this command).
    let receipt_dir = crate::config::data_dir();
    for id in [
        "binary",
        "install_prefix",
        "install_scripts",
        "install_data",
        "env",
        "service",
    ] {
        crate::defender::footprint::remove(&receipt_dir, id);
    }

    println!("Cloto uninstalled.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn engine_name() -> &'static str {
        crate::managers::installer::binary_name()
    }

    #[test]
    fn stage_engine_copies_the_engine_beside_the_kernel() {
        let src = tempfile::tempdir().unwrap();
        let prefix = tempfile::tempdir().unwrap();
        std::fs::write(src.path().join(engine_name()), b"engine").unwrap();

        let staged = stage_engine(src.path(), prefix.path()).unwrap();
        let dst = prefix.path().join(engine_name());
        assert_eq!(staged.as_deref(), Some(dst.as_path()));
        assert_eq!(std::fs::read(&dst).unwrap(), b"engine");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_ne!(
                std::fs::metadata(&dst).unwrap().permissions().mode() & 0o111,
                0
            );
        }
    }

    #[test]
    fn stage_engine_reports_a_missing_engine_instead_of_failing() {
        let src = tempfile::tempdir().unwrap();
        let prefix = tempfile::tempdir().unwrap();
        assert!(stage_engine(src.path(), prefix.path()).unwrap().is_none());
        assert!(!prefix.path().join(engine_name()).exists());
    }

    #[test]
    fn stage_engine_is_a_no_op_when_already_in_place() {
        let prefix = tempfile::tempdir().unwrap();
        std::fs::write(prefix.path().join(engine_name()), b"engine").unwrap();
        let staged = stage_engine(prefix.path(), prefix.path()).unwrap();
        assert!(staged.is_some());
        assert_eq!(
            std::fs::read(prefix.path().join(engine_name())).unwrap(),
            b"engine"
        );
    }
}
